export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import { brown } from '@mui/material/colors';

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        style={{ backgroundColor: brown[50] }}
      >{children}</body>
    </html >
  )
}
